umap/umap_.py
I also updated the documentation of `UMAP` and `simplicial_set_embedding` to account for the new parameter `negative_sample_rate`, instead of the old `n_edge_samples`.
=> Added access to high-dimensional simplicial set through class UMAP

Makefile, doc/.gitignore, doc/conf.py, docs_requirements.txt
This PR has a few updates so the docs will render on gh-pages.
=> Docs build for gh-pages

umap/umap_.py
Replaced `n_neighbors` and `self.n_neighbors` with `self._n_neighbors` in both `fit` and `transform` of UMAP class
=> Fix issue #117

doc/faq.rst
This is just a micro PR to fix a broken link. That's all :)
=> Fixed broken link to smallvis

doc/parameters.rst, umap/umap_.py
Fixes #131
Fix spelling of russellrao; List all metrics
* Updated the list of metrics based on the ValueError produced when
calling an incorrect error.
=> Docs updates for available metrics

doc/how_umap_works.rst
After reading this enlightening document, I thought I would contribute back a few typos and such I spotted along the way.
I'll create a separate pull request for the issue I broached on line 108, regarding the plurality of the word 'data', unless you are firmly in the camp of "data is an it."
=> Fix various typos and grammar issues

README.rst
This is a super minor PR. Lowest priority possible :)
=> Fix broken link to the license

umap/tests/test_umap.py, umap/umap_.py
This PR is related to #198.
I hope I got it right 😄
=> [Fixes #198] x and y are required to be the same length

umap/umap_.py, umap/utils.py
Refactor of the timestamp function. Also note when the RP-forest and nn-descent phases start, which was invaluable when tracking down the cause of #99.
=> Extract timestamp into function.

README.rst
Update the README file for the part about clustering on UMAP results.
=> Update README for clustering

doc/faq.rst
See here: #227 
Also fixed some typos and added a link to the reticulate documentation.
=> Updated FAQ for R UMAP implementations

.gitignore, umap/distances.py
first pass at my request in https://github.com/lmcinnes/umap/issues/205
=> [wip] Rc poincare

umap/umap_.py
Use random_state param instead of np.random, fix #238.
=> Use random_state param (#238)

examples/plot_mnist_example.py
fetch_mldata is deprecated and would timeout on download.
ref:
https://scikit-learn.org/stable/whats_new.html#id52
=> fix mnist example with fetch_openml since fetch_mldata is now down

doc/how_umap_works.rst, doc/transform.rst
Fix a formula that was not formatted correctly.
=> DOC: fix formatting of latex formula

doc/faq.rst
=> Fix order of algorithms in caption to be less confusing

umap/plot.py
Implementation of https://github.com/lmcinnes/umap/issues/337
=> Add ability to plot subset of points in interactive plotting

umap/umap_.py
The errors didn't match the conditions that were being checked.
=> Correcting some validation message errors in _validate_parameters.

umap/plot.py
=> Default show_legend to False when calling umap.plot.connectivity with show_points = True.

umap/plot.py
Do the same thing as https://github.com/lmcinnes/umap/issues/337 but for the non-interactive method.
=> Add subset_points argument to points plotting method

umap/umap_.py
Fix for issue https://github.com/lmcinnes/umap/issues/353
=> Fix syntax typo in hellinger check

umap/plot.py
Fix for https://github.com/lmcinnes/umap/issues/361
=> Make subset_plots more robust

.pep8speaks.yml
=> Relax pep8speaks constraints to be compatible with black

README.rst
Just fixing a little typo
(issue #388)
=> Fix #388 : Typo in umap.plot example

umap/spectral.py
=> fix sparse_named_distances iteration

doc/basic_usage.rst
=> Replace Iris references with Penguins in docs

doc/basic_usage.rst
=> Re-fix penguin images

umap/umap_.py
This PR would add a wrapper method UMAP._fit_embed_data  around function simplicial_set_embedding in UMAP.fit that can be replaced in a child.
=> added wrapper method UMAP._fit_embed_data 

doc/clustering.rst
change fetch_openml to load MNIST instead of Fashion-MNIST as the rest of the example refers to the MNIST data
=> Bug fixing in Clustering documentation

umap/parametric_umap.py
Pulls the code from https://github.com/lmcinnes/umap/issues/655 to allow precomputed metric in parametric UMAP
=> Add precomputed parametric

umap/umap_.py
=> Fix bug with jaccard distance transform on small datasets

examples/galaxy10sdss.py
follows https://umap-learn.readthedocs.io/en/latest/clustering.html
=> add clustering using hdbscan

doc/conf.py, examples/inverse_transform_example.py, umap/__init__.py, umap/aligned_umap.py, umap/layouts.py, umap/parametric_umap.py, umap/plot.py, umap/sparse.py, umap/spectral.py, umap/tests/test_composite_models.py, umap/tests/test_densmap.py, umap/tests/test_umap_nn.py, umap/tests/test_umap_on_iris.py, umap/tests/test_umap_ops.py, umap/tests/test_umap_validation_params.py, umap/umap_.py, umap/utils.py
Fixes #741 
- **num_neighbours** replaced by **row_sum** in _init_graph_transform_.
- **move_other** now an optional argument in _optimize_layout_ functions.
- **move_other=True** in _fit_transform_ code path.
- Ran black on code.
=> Potential Fix for Issue #741 (Transform not giving expected results for similar data #741)

doc/aligned_umap_basic_usage.rst
=> A wee typo

umap/aligned_umap.py
=> Use labels in AlignedUMAP if provided

umap/distances.py
Fixes https://github.com/lmcinnes/umap/issues/805
=> Properly escape invalid escape sequences.

doc/how_umap_works.rst
an k-dimensional -> a k-dimensional
=> super minor grammar

doc/mutual_nn_umap.rst
Fixing the header in the Mutual NN doc as it was initially incorrectly formated
=> Fix header for Mutual NN Doc 

umap/aligned_umap.py, umap/umap_.py
Result needs to be of type np.bool_ for boolean array indexing to work.
Fixes #876.
=> Fix in1d() return type issue

umap/aligned_umap.py
=> Fix use of relation_dicts in expand_relations

umap/aligned_umap.py
=> Fix indexing issue with relations array

umap/parametric_umap.py, umap/plot.py, umap/spectral.py, umap/umap_.py, umap/utils.py
This PR fixes some typos in the docstrings of a few functions. 😇
=> Fix typos in docstrings

setup.py
My head hurts whenever I start reading about dependency management in python, but is the `install_requires` in `setup.py` intended to keep track with changes in `requirements.txt`? If so, here is a PR.
=> consistency between install_requires and requirements.txt

umap/tests/test_umap_get_feature_names_out.py, umap/umap_.py
=> `get_feature_names_out` for `UMAP` + tests

umap/umap_.py
Anecdotally I found that function `init_graph_transform` was rather slow. I made a couple of simple changes that seemed to speed up my particular use case. 
It shouldn't be hard to verify that the changes are (or aren't) correct.
=> Minor performance improvements

umap/utils.py
=> Anticipate stricter asarray handling in numpy

umap/plot.py
Addresses #1011.
Updates capitalization issue for plotting functionality to address recent Bokeh version update to 3.1.1.
=> Plotting Fix: fixing capitalization for Bokeh plotting for version 3.1.1 compatibility

umap/umap_.py
=> Issue warning if setting n_jobs and random_state

umap/umap_.py
=> docs : Fix formatting  in UMAP class documentation

doc/precomputed_k-nn.rst
=> [TYPO] Update precomputed_k-nn.rst

setup.py, umap/parametric_umap.py, umap/tests/test_parametric_umap.py
I've tested basic use cases but there may be more needed. Also, docs may need to be updated as well.
This makes the code work with both Keras 2 and Keras 3 with the TF backend.
=> Add Keras 3 support to ParametricUMAP

umap/parametric_umap.py
This finishes the planned changes for ParametricUMAP. This PR branches off #1104. We can merge #1104 first to get a smaller diff here.
Summary:
- Supports TF, JAX, torch
- Keras 3 only
- Less code than before, and less complexity
Note that, because the changes are extensive, I'm not 100% sure whether the unit tests are quite enough to validate correctness.
=> Finish refactoring ParametricUMAP

doc/parameters.rst
Inspired by https://github.com/lmcinnes/umap/issues/61
=> docs: mention "precomputed" metric as a parameter

umap/layouts.py
Hi this is a simple fix which makes `optimize_layout_euclidean_single_epoch` to be compiled once per python process life time. 
In some cases we need to run UMAP thousands of times on datasets of order 100-1000 points. Since these datasets are very small umap  usually needs a fraction of second to complete, but because we have to `numba.njit` each time we have to wait for the result approximately 0.5 second. 
In our case we have to run umap let's say 10k times, which gives about extra 80 minutes to such process.
=> Compile _optimize_layout_euclidean_single_epoch once

doc/precomputed_k-nn.rst
=> [MINOR:TYPO] Update precomputed_k-nn.rst
